# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.3'

gem 'rails'
gem 'propshaft'
gem 'sqlite3'
gem 'puma'
gem 'fenetre', path: '../..' 

gem 'importmap-rails'
gem 'redis'
gem 'stimulus-rails'
gem 'turbo-rails'

group :development, :test do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
end
