# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.3'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 8.0.2'
# The modern asset pipeline for Rails [https://github.com/rails/propshaft]
gem 'propshaft'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '>= 2.1'
# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '>= 5.0'

# Add Fenetre gem from the parent directory
gem 'fenetre', path: '..' # Use relative path

# Dependencies needed by Fenetre are now in the root Gemfile
# gem "turbo-rails"
# gem "stimulus-rails"
# gem "redis", ">= 4.0" # For Action Cable
# gem "importmap-rails" # For JS management

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
end
