AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'test/dummy/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'coverage/**/*'

# Use plugins instead of require as per RuboCop recommendation
plugins:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-capybara

# Disable complexity and line length checks as requested
Layout/LineLength:
  Enabled: false

# Metrics cops - disabling all complexity metrics
Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Style cops - keeping more expressive style choices
Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enforce: true

Style/OpenStructUse:
  Enabled: false

# Configure Minitest specific cops
Minitest/MultipleAssertions:
  Enabled: false

# Keep assertions readable
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Minitest/AssertPredicate:
  Enabled: false

# Configure Capybara specific cops
Capybara/ClickLinkOrButtonStyle:
  Enabled: true

Capybara/SpecificMatcher:
  Enabled: true

# Gemspec settings
Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
